name: Pipeline  
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar o Poetry
        run: pipx install poetry

      - name: Instalar dependencias do projeto
        run: poetry install

      - name: Executar os testes unitários
        run: poetry run task test