name: Pipeline  
on: [push, pull_request]

jobs:
  test:
    run-on: ubuntu-latest

    steps:
      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'